/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/luka/dev/provability_sat/nimcache/stdlib_sharedlist.o /home/luka/dev/provability_sat/nimcache/stdlib_sharedlist.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef long tyArray_xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist)(pthread_mutex_t* lock);

static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist)(pthread_mutex_t* lock) {
	pthread_mutex_init(lock, NIM_NIL);
}

N_NIMCALL(tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw, initSharedList_ftyWlQN9a0f9cDyTF3NRz9cTg)(void) {
	tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw result;
	memset((void*)(&result), 0, sizeof(result));
	initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist((&result.lock));
	result.head = NIM_NIL;
	result.tail = NIM_NIL;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistDatInit000)(void) {
}

