/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/luka/dev/provability_sat/nimcache/stdlib_math.o /home/luka/dev/provability_sat/nimcache/stdlib_math.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_5KA8IvyQawZZLaFtv3B0ZQ tyTuple_5KA8IvyQawZZLaFtv3B0ZQ;
struct tyTuple_5KA8IvyQawZZLaFtv3B0ZQ {
NI Field0;
NI Field1;
};
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y);

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

N_NIMCALL(NI, roof__quCe21GD6ES9cmTsTs9cYP7Q)(NI x, NI y) {
	NI result;
	tyTuple_5KA8IvyQawZZLaFtv3B0ZQ T1_;
	NI x_2;
	NI y_2;
	result = (NI)0;
	T1_.Field0 = x;
	T1_.Field1 = y;
	x_2 = T1_.Field0;
	y_2 = T1_.Field1;
	result = ((NI) 1);
	{
		while (1) {
			{
				if (!!((((NI) ((NI)(((NI) (y_2)) & ((NI) 1)))) == ((NI) 0)))) goto LA6_;
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath((&result), x_2);
			}
			LA6_: ;
			y_2 = ((NI) ((NI)((NU64)(((NI) (y_2))) >> (NU64)(((NI) 1)))));
			{
				if (!(((NI) (y_2)) == ((NI) 0))) goto LA10_;
				goto LA2;
			}
			LA10_: ;
			stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath((&x_2), x_2);
		}
	} LA2: ;
	return result;
}

N_NIMCALL(NI, sum_gbIPXmHbH9cB6gW9ceVVFvbQ)(NI* x, NI xLen_0) {
	NI result;
	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				i = x[i_2];
				result = (NI)(result + i);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void) {
}

