/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/luka/dev/provability_sat/nimcache/stdlib_threadpool.o /home/luka/dev/provability_sat/nimcache/stdlib_threadpool.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <pthread.h>
#include <sys/types.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw;
typedef struct tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw;
typedef struct tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw;
typedef struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw;
typedef struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg;
typedef struct tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA;
typedef struct tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw;
typedef long long tyArray_xLtLuIT9aUkeKRzzMNC75Vw[6];
typedef long tyArray_xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
typedef N_NIMCALL_PTR(void, tyProc_nSqh6BBL9cSEu9bcR48Z72QA) (tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* m);
struct tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw {
tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg* core;
unsigned long sys;
tyProc_nSqh6BBL9cSEu9bcR48Z72QA dataFn;
tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* data;
};
typedef tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw tyArray_TsQaT6n8o7agBt1qVLDj8w[256];
typedef N_NIMCALL_PTR(void, tyProc_fhqfcnDhIcLpBpSTVsWEZg) (void* thread, void* args);
typedef void* tyArray_2PWyF6nokyTyhzmcY3ON3w[128];
struct tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw {
NI len;
pthread_mutex_t lock;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw empty;
tyArray_2PWyF6nokyTyhzmcY3ON3w data;
};
struct tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw {
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw taskArrived;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw taskStarted;
tyProc_fhqfcnDhIcLpBpSTVsWEZg f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw q;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw readyForTask;
};
typedef tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw tyArray_5sGw9aMSI320X9cbYIDJFEOQ[256];
typedef tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw tyArray_Vf5imvkL6TAbxWABRfm20A[32];
typedef tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw tyArray_W9bX58rb2TvIPS9bAprPBVQg[32];
struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA {
NI calls;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg {
  RootObj Sup;
NIM_BOOL ready;
NIM_BOOL usesSemaphore;
NIM_BOOL awaited;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA* ai;
NI idx;
void* data;
void* owner;
};
struct tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA {
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
NI idx;
};
struct tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw {
  tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg Sup;
NI blob;
};
typedef NU8 tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig;
struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg {
char dummy;
};
static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist)(pthread_mutex_t* lock);
N_NIMCALL(void, initSemaphore_9czoqdg4eHIgtJ4wssK5YHA)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, initCond_cET5UPJTPSiflmV7IZS68Athreadpool)(pthread_cond_t* cond);
N_NIMCALL(void, setup_p4oO1XgRwu6WxNojgsXntg)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NOINLINE(void, activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg)(NI i);
N_NIMCALL(void, createThread_M9ct0f7CQiyyVF9ahBe3fSlw)(tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw* t, tyProc_nSqh6BBL9cSEu9bcR48Z72QA tp, tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* param);
N_NIMCALL(void, slave_ZLEiMrITYl7xqyEhA5iC1g)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
N_NIMCALL(void, signal_9czoqdg4eHIgtJ4wssK5YHA_2)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
N_NIMCALL(void, acquire_c9cbvs4ShkxrwmQmnY63PGA)(pthread_mutex_t* lock);
N_NIMCALL(void, release_c9cbvs4ShkxrwmQmnY63PGA_2)(pthread_mutex_t* lock);
static N_INLINE(void, signal_cET5UPJTPSiflmV7IZS68A_2threadpool)(pthread_cond_t* cond);
N_NIMCALL(void, await_9czoqdg4eHIgtJ4wssK5YHA_3)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, wait_1jWf7NqlMVz9aQJMRL9bTm9bQthreadpool)(pthread_cond_t* cond, pthread_mutex_t* lock);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
N_NIMCALL(void, nimGCunref)(void* p);
static N_INLINE(NI, atomicDec_4E9cxwuunx9aiL7vj9bdy8WvAthreadpool)(NI* memLoc, NI x);
static N_NIMCALL(void, Marker_tyRef_h9bIytcalWPxjGLnx0PXmCg)(void* p, NI op);
N_NIMCALL(void, fvFinalizer_Qu41eVSk9cKgFEnpH5hYc8Q)(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw* fv);
N_NIMCALL(void, finished_v7HeuUBcnpz8vQGjcNl2Zg)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
N_NIMCALL(void, await_v7HeuUBcnpz8vQGjcNl2Zg_2)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
static N_INLINE(void, destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, deinitCond_cET5UPJTPSiflmV7IZS68A_3threadpool)(pthread_cond_t* cond);
static N_INLINE(void, deinitLock_NyibMGWEvLI6dmuAjxN9brAthreadpool)(pthread_mutex_t* lock);
N_NIMCALL(void, wakeupWorkerToProcessQueue_YsEpsvk4M2H0cFOPo7KYiA_2)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
static N_INLINE(void, cpuRelax_IZ2oOmqdsYQ7vixQGKSDcAthreadpool)(void);
N_NIMCALL(void, colonanonymous__RN9c4f80Dl8mVIo1K9bSACqA)(void* w, void* a);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NIM_BOOL, selectWorker_BW1ODxSJ4rN4KmfdYS8AFw)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data);
N_NIMCALL(NIM_BOOL, tryAcquire_9bPySkj6HXfWNB4ampKcs9bg)(pthread_mutex_t* lock);
N_NIMCALL(tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA* s);
static N_INLINE(NI, atomicInc_4E9cxwuunx9aiL7vj9bdy8WvA_2threadpool)(NI* memLoc, NI x);
NI currentPoolSize_ErccdOg9batM6rAb3hYbfxA;
NI maxPoolSize_I5gWiq7COu2xfOvex9aGTWw;
NI minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw gSomeReady_RyUdpNfPQUpKmQaHtWHYoA;
tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* readyWorker_BT69aUhVoxO4qq9b8EinSVNA;
pthread_mutex_t numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA;
NI numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw;
NI numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg;
NIM_THREADVAR NIM_BOOL isSlave_t9a8wsVVRYqGEKhg1vb49b3g;
tyArray_TsQaT6n8o7agBt1qVLDj8w workers_bezHuru9a1bEti2XBmfodvA;
tyArray_5sGw9aMSI320X9cbYIDJFEOQ workersData_R5YxoJYCt3PvKeJGhluUDQ;
tyArray_Vf5imvkL6TAbxWABRfm20A distinguished_PEEgL9bODGVNNubj61abNQA;
tyArray_W9bX58rb2TvIPS9bAprPBVQg distinguishedData_Lqsi7ieuVktaO9acMSZyorQ;
tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA state_7PVqgO4qfT36l9bZ9a9cqhD9bA;
pthread_mutex_t stateLock_Of3qxka1C2uLE9anKCj52kA;
pthread_mutex_t distinguishedLock_lPmqsqhMalxIWA0zwhlpFg;
TNimType NTI_AqHEWWcw2VBFjoa2Hp8Akw_;
TNimType NTI_sx9abLHOwgGDBH9bpoqw2ezw_;
extern TNimType NTI_keOjwH3s9bnYBEeyteQLwbw_;
extern TNimType NTI_9bxnxao7MiiLOwO9aLAh9a3og_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_fhqfcnDhIcLpBpSTVsWEZg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_5COJP8EWIaAuXvZlDbQZmw_;
TNimType NTI_2PWyF6nokyTyhzmcY3ON3w_;
TNimType NTI_CyNApV6Mfiphj5eUnH5G1A_;
extern NIM_THREADVAR TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_CJfwFDAb1ST4bu6G9bMAYbg_;
TNimType NTI_InuzBj4ASNnb8C8ZpRzfbA_;
TNimType NTI_lFbunaQx9b6UMGaLkOEMqfQ_;
TNimType NTI_Wi7KCtOkgrq64t5MzTOrhw_;
TNimType NTI_h9bIytcalWPxjGLnx0PXmCg_;
STRING_LITERAL(TM_Qzgg5NBLvccay07XFph3Rw_9, "isNil(fv.ai) flowVar is still attached to an \'awaitAny\'", 55);

static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist)(pthread_mutex_t* lock) {
	pthread_mutex_init(lock, NIM_NIL);
}

static N_INLINE(void, initCond_cET5UPJTPSiflmV7IZS68Athreadpool)(pthread_cond_t* cond) {
	pthread_cond_init(cond, NIM_NIL);
}

N_NIMCALL(void, initSemaphore_9czoqdg4eHIgtJ4wssK5YHA)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	initCond_cET5UPJTPSiflmV7IZS68Athreadpool((&(*cv).c));
	initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist((&(*cv).L));
}

static N_INLINE(void, signal_cET5UPJTPSiflmV7IZS68A_2threadpool)(pthread_cond_t* cond) {
	pthread_cond_signal(cond);
}

N_NIMCALL(void, signal_9czoqdg4eHIgtJ4wssK5YHA_2)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*cv).L));
	(*cv).counter += ((NI) 1);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*cv).L));
	signal_cET5UPJTPSiflmV7IZS68A_2threadpool((&(*cv).c));
}

static N_INLINE(void, wait_1jWf7NqlMVz9aQJMRL9bTm9bQthreadpool)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	pthread_cond_wait(cond, lock);
}

N_NIMCALL(void, await_9czoqdg4eHIgtJ4wssK5YHA_3)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*cv).L));
	{
		while (1) {
			if (!((*cv).counter <= ((NI) 0))) goto LA2;
			wait_1jWf7NqlMVz9aQJMRL9bTm9bQthreadpool((&(*cv).c), (&(*cv).L));
		} LA2: ;
	}
	(*cv).counter -= ((NI) 1);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*cv).L));
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

N_NIMCALL(void, cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw* q;
	q = (&(*w).q);
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*q).lock));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((*q).len - 1);
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				nimGCunref(((RootObj*) ((*q).data[(i)- 0])));
				res += ((NI) 1);
			} LA3: ;
		}
	}
	(*q).len = ((NI) 0);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*q).lock));
}

static N_INLINE(NI, atomicDec_4E9cxwuunx9aiL7vj9bdy8WvAthreadpool)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = __atomic_sub_fetch(memLoc, x, __ATOMIC_RELAXED);
	return result;
}

N_NIMCALL(void, slave_ZLEiMrITYl7xqyEhA5iC1g)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	isSlave_t9a8wsVVRYqGEKhg1vb49b3g = NIM_TRUE;
	{
		while (1) {
			TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_5;
			TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_6;
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			readyWorker_BT69aUhVoxO4qq9b8EinSVNA = w;
			signal_9czoqdg4eHIgtJ4wssK5YHA_2((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
			await_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w).taskArrived));
			acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_5);
			TM_Qzgg5NBLvccay07XFph3Rw_5.status = setjmp(TM_Qzgg5NBLvccay07XFph3Rw_5.context);
			if (TM_Qzgg5NBLvccay07XFph3Rw_5.status == 0) {
				numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw += ((NI) 1);
				popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			}
			if (TM_Qzgg5NBLvccay07XFph3Rw_5.status != 0) reraiseException();
			(*w).f(((void*) (w)), (*w).data);
			acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_6);
			TM_Qzgg5NBLvccay07XFph3Rw_6.status = setjmp(TM_Qzgg5NBLvccay07XFph3Rw_6.context);
			if (TM_Qzgg5NBLvccay07XFph3Rw_6.status == 0) {
				numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw -= ((NI) 1);
				popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			}
			if (TM_Qzgg5NBLvccay07XFph3Rw_6.status != 0) reraiseException();
			{
				if (!!(((*w).q.len == ((NI) 0)))) goto LA11_;
				cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA(w);
			}
			LA11_: ;
			{
				NI T17_;
				if (!(*w).shutdown) goto LA15_;
				(*w).shutdown = NIM_FALSE;
				T17_ = (NI)0;
				T17_ = atomicDec_4E9cxwuunx9aiL7vj9bdy8WvAthreadpool((&currentPoolSize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
			}
			LA15_: ;
		}
	}
}

N_NOINLINE(void, activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg)(NI i) {
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].taskArrived));
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].taskStarted));
	workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].initialized = NIM_TRUE;
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].q.empty));
	initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].q.lock));
	createThread_M9ct0f7CQiyyVF9ahBe3fSlw((&workers_bezHuru9a1bEti2XBmfodvA[(i)- 0]), slave_ZLEiMrITYl7xqyEhA5iC1g, (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]));
}

N_NIMCALL(void, setup_p4oO1XgRwu6WxNojgsXntg)(void) {
	NI p;
	p = ncpicountProcessors();
	currentPoolSize_ErccdOg9batM6rAb3hYbfxA = ((p <= ((NI) 256)) ? p : ((NI) 256));
	readyWorker_BT69aUhVoxO4qq9b8EinSVNA = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(((NI) 0))- 0]);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (currentPoolSize_ErccdOg9batM6rAb3hYbfxA - 1);
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg(i);
				res += ((NI) 1);
			} LA3: ;
		}
	}
}
static N_NIMCALL(void, Marker_tyRef_h9bIytcalWPxjGLnx0PXmCg)(void* p, NI op) {
	tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw* a;
	NI T1_;
	NI T2_;
	a = (tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw*)p;
	T1_ = (NI)0;
	T2_ = (NI)0;
}

static N_INLINE(void, deinitCond_cET5UPJTPSiflmV7IZS68A_3threadpool)(pthread_cond_t* cond) {
	pthread_cond_destroy(cond);
}

static N_INLINE(void, deinitLock_NyibMGWEvLI6dmuAjxN9brAthreadpool)(pthread_mutex_t* lock) {
	pthread_mutex_destroy(lock);
}

static N_INLINE(void, destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	deinitCond_cET5UPJTPSiflmV7IZS68A_3threadpool((&(*cv).c));
	deinitLock_NyibMGWEvLI6dmuAjxN9brAthreadpool((&(*cv).L));
}

N_NIMCALL(void, await_v7HeuUBcnpz8vQGjcNl2Zg_2)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (*fv).usesSemaphore;
		if (!(T3_)) goto LA4_;
		T3_ = !((*fv).awaited);
		LA4_: ;
		if (!T3_) goto LA5_;
		(*fv).awaited = NIM_TRUE;
		await_9czoqdg4eHIgtJ4wssK5YHA_3((&(*fv).cv));
		destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&(*fv).cv));
	}
	LA5_: ;
}

static N_INLINE(void, cpuRelax_IZ2oOmqdsYQ7vixQGKSDcAthreadpool)(void) {
	asm volatile("pause" ::: "memory");
}

N_NIMCALL(void, colonanonymous__RN9c4f80Dl8mVIo1K9bSACqA)(void* w, void* a) {
	tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w_2;
	w_2 = ((tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*) (w));
	cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA(w_2);
	signal_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w_2).q.empty));
}

N_NIMCALL(void, wakeupWorkerToProcessQueue_YsEpsvk4M2H0cFOPo7KYiA_2)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
			if (!!(T3_)) goto LA2;
			cpuRelax_IZ2oOmqdsYQ7vixQGKSDcAthreadpool();
		} LA2: ;
	}
	(*w).data = NIM_NIL;
	(*w).f = colonanonymous__RN9c4f80Dl8mVIo1K9bSACqA;
	signal_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w).taskArrived));
}

N_NIMCALL(void, finished_v7HeuUBcnpz8vQGjcNl2Zg)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* owner;
	tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw* q;
{	{
		if (!!(((*fv).ai == 0))) goto LA3_;
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_Qzgg5NBLvccay07XFph3Rw_9));
	}
	LA3_: ;
	await_v7HeuUBcnpz8vQGjcNl2Zg_2(fv);
	{
		if (!((*fv).data == 0)) goto LA7_;
		goto BeforeRet_;
	}
	LA7_: ;
	owner = ((tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*) ((*fv).owner));
	q = (&(*owner).q);
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*q).lock));
	{
		while (1) {
			if (!!(((*q).len < ((NI) 128)))) goto LA10;
			release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*q).lock));
			wakeupWorkerToProcessQueue_YsEpsvk4M2H0cFOPo7KYiA_2(owner);
			await_9czoqdg4eHIgtJ4wssK5YHA_3((&(*q).empty));
			acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*q).lock));
		} LA10: ;
	}
	(*q).data[((*q).len)- 0] = ((void*) ((*fv).data));
	(*q).len += ((NI) 1);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*q).lock));
	(*fv).data = NIM_NIL;
	}BeforeRet_: ;
}

N_NIMCALL(void, fvFinalizer_Qu41eVSk9cKgFEnpH5hYc8Q)(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw* fv) {
	tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* T1_;
	T1_ = (tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg*)0;
	T1_ = &fv->Sup;
	finished_v7HeuUBcnpz8vQGjcNl2Zg(T1_);
}

N_NIMCALL(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw*, nimCreateFlowVar_OCQFeMap3nldIDVKovDfqQ)(void) {
	tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw* result;
	result = (tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw*)0;
	result = (tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw*) newObj((&NTI_h9bIytcalWPxjGLnx0PXmCg_), sizeof(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw));
	(*result).Sup.Sup.m_type = (&NTI_Wi7KCtOkgrq64t5MzTOrhw_);
	return result;
}

N_NIMCALL(void, nimFlowVarCreateSemaphore)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&(*fv).cv));
	(*fv).usesSemaphore = NIM_TRUE;
}

N_NIMCALL(NIM_BOOL, selectWorker_BW1ODxSJ4rN4KmfdYS8AFw)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
		if (!T3_) goto LA4_;
		(*w).data = data;
		(*w).f = fn;
		signal_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w).taskArrived));
		await_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w).taskStarted));
		result = NIM_TRUE;
	}
	LA4_: ;
	return result;
}

static N_INLINE(NI, atomicInc_4E9cxwuunx9aiL7vj9bdy8WvA_2threadpool)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = __atomic_add_fetch(memLoc, x, __ATOMIC_RELAXED);
	return result;
}

N_NIMCALL(void, nimSpawn3)(tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
{	{
		while (1) {
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw(readyWorker_BT69aUhVoxO4qq9b8EinSVNA, fn, data);
				if (!T5_) goto LA6_;
				goto BeforeRet_;
			}
			LA6_: ;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (currentPoolSize_ErccdOg9batM6rAb3hYbfxA - 1);
				res = ((NI) 0);
				{
					while (1) {
						if (!(res <= colontmp_)) goto LA10;
						i = res;
						{
							NIM_BOOL T13_;
							T13_ = (NIM_BOOL)0;
							T13_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]), fn, data);
							if (!T13_) goto LA14_;
							goto BeforeRet_;
						}
						LA14_: ;
						res += ((NI) 1);
					} LA10: ;
				}
			}
			{
				NIM_BOOL T18_;
				T18_ = (NIM_BOOL)0;
				T18_ = (state_7PVqgO4qfT36l9bZ9a9cqhD9bA.calls < maxPoolSize_I5gWiq7COu2xfOvex9aGTWw);
				if (T18_) goto LA19_;
				T18_ = (((NI) ((NI)(state_7PVqgO4qfT36l9bZ9a9cqhD9bA.calls & ((NI) 127)))) == ((NI) 0));
				LA19_: ;
				if (!T18_) goto LA20_;
				{
					NIM_BOOL T24_;
					tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig T27_;
					T24_ = (NIM_BOOL)0;
					T24_ = tryAcquire_9bPySkj6HXfWNB4ampKcs9bg((&stateLock_Of3qxka1C2uLE9anKCj52kA));
					if (!T24_) goto LA25_;
					T27_ = (tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;
					T27_ = advice_uXlfLohkC9aBvpzhcIrG9amw((&state_7PVqgO4qfT36l9bZ9a9cqhD9bA));
					switch (T27_) {
					case ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0):
					{
					}
					break;
					case ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1):
					{
						{
							tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w;
							NI T38_;
							if (!(currentPoolSize_ErccdOg9batM6rAb3hYbfxA < maxPoolSize_I5gWiq7COu2xfOvex9aGTWw)) goto LA32_;
							{
								if (!!(workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA36_;
								activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg(currentPoolSize_ErccdOg9batM6rAb3hYbfxA);
							}
							LA36_: ;
							w = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0]);
							T38_ = (NI)0;
							T38_ = atomicInc_4E9cxwuunx9aiL7vj9bdy8WvA_2threadpool((&currentPoolSize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							{
								NIM_BOOL T41_;
								T41_ = (NIM_BOOL)0;
								T41_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw(w, fn, data);
								if (!T41_) goto LA42_;
								release_c9cbvs4ShkxrwmQmnY63PGA_2((&stateLock_Of3qxka1C2uLE9anKCj52kA));
								goto BeforeRet_;
							}
							LA42_: ;
						}
						LA32_: ;
					}
					break;
					case ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2):
					{
						{
							tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w_2;
							if (!(minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg < currentPoolSize_ErccdOg9batM6rAb3hYbfxA)) goto LA47_;
							w_2 = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[((NI)(currentPoolSize_ErccdOg9batM6rAb3hYbfxA - ((NI) 1)))- 0]);
							(*w_2).shutdown = NIM_TRUE;
						}
						LA47_: ;
					}
					break;
					}
					release_c9cbvs4ShkxrwmQmnY63PGA_2((&stateLock_Of3qxka1C2uLE9anKCj52kA));
				}
				LA25_: ;
			}
			LA20_: ;
			{
				TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_10;
				if (!isSlave_t9a8wsVVRYqGEKhg1vb49b3g) goto LA51_;
				acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_10);
				TM_Qzgg5NBLvccay07XFph3Rw_10.status = setjmp(TM_Qzgg5NBLvccay07XFph3Rw_10.context);
				if (TM_Qzgg5NBLvccay07XFph3Rw_10.status == 0) {
					{
						if (!(numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw <= (NI)(numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg + ((NI) 1)))) goto LA56_;
						{
							tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w_3;
							NI T66_;
							if (!(currentPoolSize_ErccdOg9batM6rAb3hYbfxA < maxPoolSize_I5gWiq7COu2xfOvex9aGTWw)) goto LA60_;
							{
								if (!!(workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA64_;
								activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg(currentPoolSize_ErccdOg9batM6rAb3hYbfxA);
							}
							LA64_: ;
							w_3 = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0]);
							T66_ = (NI)0;
							T66_ = atomicInc_4E9cxwuunx9aiL7vj9bdy8WvA_2threadpool((&currentPoolSize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							{
								NIM_BOOL T69_;
								T69_ = (NIM_BOOL)0;
								T69_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw(w_3, fn, data);
								if (!T69_) goto LA70_;
								popSafePoint();
								release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
								goto BeforeRet_;
							}
							LA70_: ;
						}
						goto LA58_;
						LA60_: ;
						{
						}
						LA58_: ;
					}
					LA56_: ;
					numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg += ((NI) 1);
					popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				}
				if (TM_Qzgg5NBLvccay07XFph3Rw_10.status != 0) reraiseException();
			}
			LA51_: ;
			await_9czoqdg4eHIgtJ4wssK5YHA_3((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
			{
				TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_11;
				if (!isSlave_t9a8wsVVRYqGEKhg1vb49b3g) goto LA77_;
				acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_11);
				TM_Qzgg5NBLvccay07XFph3Rw_11.status = setjmp(TM_Qzgg5NBLvccay07XFph3Rw_11.context);
				if (TM_Qzgg5NBLvccay07XFph3Rw_11.status == 0) {
					numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg -= ((NI) 1);
					popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				}
				if (TM_Qzgg5NBLvccay07XFph3Rw_11.status != 0) reraiseException();
			}
			LA77_: ;
		}
	}
	}BeforeRet_: ;
}

N_NIMCALL(void, nimArgsPassingDone)(void* p) {
	tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w;
	w = ((tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*) (p));
	signal_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w).taskStarted));
}

N_NIMCALL(void, nimFlowVarSignal)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	{
		if (!!(((*fv).ai == NIM_NIL))) goto LA3_;
		acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*(*fv).ai).cv.L));
		(*(*fv).ai).idx = (*fv).idx;
		(*(*fv).ai).cv.counter += ((NI) 1);
		release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*(*fv).ai).cv.L));
		signal_cET5UPJTPSiflmV7IZS68A_2threadpool((&(*(*fv).ai).cv.c));
	}
	LA3_: ;
	{
		if (!(*fv).usesSemaphore) goto LA7_;
		signal_9czoqdg4eHIgtJ4wssK5YHA_2((&(*fv).cv));
	}
	LA7_: ;
}

N_NIMCALL(NI, roof__EQj7z8t1CqKT1SYOeiVsTA)(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw* fv) {
	NI result;
	tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* T1_;
	result = (NI)0;
	T1_ = (tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg*)0;
	T1_ = &fv->Sup;
	await_v7HeuUBcnpz8vQGjcNl2Zg_2(T1_);
	result = (*fv).blob;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void) {
	maxPoolSize_I5gWiq7COu2xfOvex9aGTWw = ((NI) 256);
	minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg = ((NI) 4);
	initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
	initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist((&stateLock_Of3qxka1C2uLE9anKCj52kA));
	initLock_NyibMGWEvLI6dmuAjxN9brAsharedlist((&distinguishedLock_lPmqsqhMalxIWA0zwhlpFg));
	setup_p4oO1XgRwu6WxNojgsXntg();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void) {
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_2[9];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_3[3];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_4[4];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_7[8];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_8[2];
static TNimNode TM_Qzgg5NBLvccay07XFph3Rw_0[32];
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.size = sizeof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw);
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.kind = 18;
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.base = 0;
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_2[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[1];
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.size = sizeof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw);
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.kind = 18;
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.base = 0;
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_3[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[3];
TM_Qzgg5NBLvccay07XFph3Rw_0[3].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[3].offset = offsetof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, c);
TM_Qzgg5NBLvccay07XFph3Rw_0[3].typ = (&NTI_keOjwH3s9bnYBEeyteQLwbw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[3].name = "c";
TM_Qzgg5NBLvccay07XFph3Rw_3[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[4];
TM_Qzgg5NBLvccay07XFph3Rw_0[4].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[4].offset = offsetof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, L);
TM_Qzgg5NBLvccay07XFph3Rw_0[4].typ = (&NTI_9bxnxao7MiiLOwO9aLAh9a3og_);
TM_Qzgg5NBLvccay07XFph3Rw_0[4].name = "L";
TM_Qzgg5NBLvccay07XFph3Rw_3[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[5];
TM_Qzgg5NBLvccay07XFph3Rw_0[5].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[5].offset = offsetof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, counter);
TM_Qzgg5NBLvccay07XFph3Rw_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[5].name = "counter";
TM_Qzgg5NBLvccay07XFph3Rw_0[2].len = 3; TM_Qzgg5NBLvccay07XFph3Rw_0[2].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[2].sons = &TM_Qzgg5NBLvccay07XFph3Rw_3[0];
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[2];
TM_Qzgg5NBLvccay07XFph3Rw_0[1].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[1].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, taskArrived);
TM_Qzgg5NBLvccay07XFph3Rw_0[1].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[1].name = "taskArrived";
TM_Qzgg5NBLvccay07XFph3Rw_2[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[6];
TM_Qzgg5NBLvccay07XFph3Rw_0[6].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[6].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, taskStarted);
TM_Qzgg5NBLvccay07XFph3Rw_0[6].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[6].name = "taskStarted";
TM_Qzgg5NBLvccay07XFph3Rw_2[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[7];
NTI_fhqfcnDhIcLpBpSTVsWEZg_.size = sizeof(tyProc_fhqfcnDhIcLpBpSTVsWEZg);
NTI_fhqfcnDhIcLpBpSTVsWEZg_.kind = 25;
NTI_fhqfcnDhIcLpBpSTVsWEZg_.base = 0;
NTI_fhqfcnDhIcLpBpSTVsWEZg_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_0[7].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[7].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, f);
TM_Qzgg5NBLvccay07XFph3Rw_0[7].typ = (&NTI_fhqfcnDhIcLpBpSTVsWEZg_);
TM_Qzgg5NBLvccay07XFph3Rw_0[7].name = "f";
TM_Qzgg5NBLvccay07XFph3Rw_2[3] = &TM_Qzgg5NBLvccay07XFph3Rw_0[8];
TM_Qzgg5NBLvccay07XFph3Rw_0[8].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[8].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, data);
TM_Qzgg5NBLvccay07XFph3Rw_0[8].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[8].name = "data";
TM_Qzgg5NBLvccay07XFph3Rw_2[4] = &TM_Qzgg5NBLvccay07XFph3Rw_0[9];
TM_Qzgg5NBLvccay07XFph3Rw_0[9].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[9].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, ready);
TM_Qzgg5NBLvccay07XFph3Rw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[9].name = "ready";
TM_Qzgg5NBLvccay07XFph3Rw_2[5] = &TM_Qzgg5NBLvccay07XFph3Rw_0[10];
TM_Qzgg5NBLvccay07XFph3Rw_0[10].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[10].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, initialized);
TM_Qzgg5NBLvccay07XFph3Rw_0[10].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[10].name = "initialized";
TM_Qzgg5NBLvccay07XFph3Rw_2[6] = &TM_Qzgg5NBLvccay07XFph3Rw_0[11];
TM_Qzgg5NBLvccay07XFph3Rw_0[11].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[11].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, shutdown);
TM_Qzgg5NBLvccay07XFph3Rw_0[11].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[11].name = "shutdown";
TM_Qzgg5NBLvccay07XFph3Rw_2[7] = &TM_Qzgg5NBLvccay07XFph3Rw_0[12];
NTI_5COJP8EWIaAuXvZlDbQZmw_.size = sizeof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw);
NTI_5COJP8EWIaAuXvZlDbQZmw_.kind = 18;
NTI_5COJP8EWIaAuXvZlDbQZmw_.base = 0;
NTI_5COJP8EWIaAuXvZlDbQZmw_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_4[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[14];
TM_Qzgg5NBLvccay07XFph3Rw_0[14].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[14].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, len);
TM_Qzgg5NBLvccay07XFph3Rw_0[14].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[14].name = "len";
TM_Qzgg5NBLvccay07XFph3Rw_4[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[15];
TM_Qzgg5NBLvccay07XFph3Rw_0[15].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[15].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, lock);
TM_Qzgg5NBLvccay07XFph3Rw_0[15].typ = (&NTI_9bxnxao7MiiLOwO9aLAh9a3og_);
TM_Qzgg5NBLvccay07XFph3Rw_0[15].name = "lock";
TM_Qzgg5NBLvccay07XFph3Rw_4[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[16];
TM_Qzgg5NBLvccay07XFph3Rw_0[16].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[16].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, empty);
TM_Qzgg5NBLvccay07XFph3Rw_0[16].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[16].name = "empty";
TM_Qzgg5NBLvccay07XFph3Rw_4[3] = &TM_Qzgg5NBLvccay07XFph3Rw_0[17];
NTI_2PWyF6nokyTyhzmcY3ON3w_.size = sizeof(tyArray_2PWyF6nokyTyhzmcY3ON3w);
NTI_2PWyF6nokyTyhzmcY3ON3w_.kind = 16;
NTI_2PWyF6nokyTyhzmcY3ON3w_.base = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
NTI_2PWyF6nokyTyhzmcY3ON3w_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_0[17].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[17].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, data);
TM_Qzgg5NBLvccay07XFph3Rw_0[17].typ = (&NTI_2PWyF6nokyTyhzmcY3ON3w_);
TM_Qzgg5NBLvccay07XFph3Rw_0[17].name = "data";
TM_Qzgg5NBLvccay07XFph3Rw_0[13].len = 4; TM_Qzgg5NBLvccay07XFph3Rw_0[13].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[13].sons = &TM_Qzgg5NBLvccay07XFph3Rw_4[0];
NTI_5COJP8EWIaAuXvZlDbQZmw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[13];
TM_Qzgg5NBLvccay07XFph3Rw_0[12].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[12].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, q);
TM_Qzgg5NBLvccay07XFph3Rw_0[12].typ = (&NTI_5COJP8EWIaAuXvZlDbQZmw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[12].name = "q";
TM_Qzgg5NBLvccay07XFph3Rw_2[8] = &TM_Qzgg5NBLvccay07XFph3Rw_0[18];
TM_Qzgg5NBLvccay07XFph3Rw_0[18].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[18].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, readyForTask);
TM_Qzgg5NBLvccay07XFph3Rw_0[18].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[18].name = "readyForTask";
TM_Qzgg5NBLvccay07XFph3Rw_0[0].len = 9; TM_Qzgg5NBLvccay07XFph3Rw_0[0].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[0].sons = &TM_Qzgg5NBLvccay07XFph3Rw_2[0];
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[0];
NTI_CyNApV6Mfiphj5eUnH5G1A_.size = sizeof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*);
NTI_CyNApV6Mfiphj5eUnH5G1A_.kind = 21;
NTI_CyNApV6Mfiphj5eUnH5G1A_.base = (&NTI_AqHEWWcw2VBFjoa2Hp8Akw_);
NTI_CyNApV6Mfiphj5eUnH5G1A_.flags = 3;
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.size = sizeof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg);
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.kind = 17;
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.flags = 1;
TM_Qzgg5NBLvccay07XFph3Rw_7[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[20];
TM_Qzgg5NBLvccay07XFph3Rw_0[20].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[20].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, ready);
TM_Qzgg5NBLvccay07XFph3Rw_0[20].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[20].name = "ready";
TM_Qzgg5NBLvccay07XFph3Rw_7[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[21];
TM_Qzgg5NBLvccay07XFph3Rw_0[21].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[21].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, usesSemaphore);
TM_Qzgg5NBLvccay07XFph3Rw_0[21].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[21].name = "usesSemaphore";
TM_Qzgg5NBLvccay07XFph3Rw_7[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[22];
TM_Qzgg5NBLvccay07XFph3Rw_0[22].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[22].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, awaited);
TM_Qzgg5NBLvccay07XFph3Rw_0[22].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[22].name = "awaited";
TM_Qzgg5NBLvccay07XFph3Rw_7[3] = &TM_Qzgg5NBLvccay07XFph3Rw_0[23];
TM_Qzgg5NBLvccay07XFph3Rw_0[23].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[23].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, cv);
TM_Qzgg5NBLvccay07XFph3Rw_0[23].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[23].name = "cv";
TM_Qzgg5NBLvccay07XFph3Rw_7[4] = &TM_Qzgg5NBLvccay07XFph3Rw_0[24];
NTI_InuzBj4ASNnb8C8ZpRzfbA_.size = sizeof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA);
NTI_InuzBj4ASNnb8C8ZpRzfbA_.kind = 18;
NTI_InuzBj4ASNnb8C8ZpRzfbA_.base = 0;
NTI_InuzBj4ASNnb8C8ZpRzfbA_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_8[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[26];
TM_Qzgg5NBLvccay07XFph3Rw_0[26].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[26].offset = offsetof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA, cv);
TM_Qzgg5NBLvccay07XFph3Rw_0[26].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[26].name = "cv";
TM_Qzgg5NBLvccay07XFph3Rw_8[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[27];
TM_Qzgg5NBLvccay07XFph3Rw_0[27].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[27].offset = offsetof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA, idx);
TM_Qzgg5NBLvccay07XFph3Rw_0[27].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[27].name = "idx";
TM_Qzgg5NBLvccay07XFph3Rw_0[25].len = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[25].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[25].sons = &TM_Qzgg5NBLvccay07XFph3Rw_8[0];
NTI_InuzBj4ASNnb8C8ZpRzfbA_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[25];
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.size = sizeof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA*);
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.kind = 21;
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.base = (&NTI_InuzBj4ASNnb8C8ZpRzfbA_);
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_0[24].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[24].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, ai);
TM_Qzgg5NBLvccay07XFph3Rw_0[24].typ = (&NTI_lFbunaQx9b6UMGaLkOEMqfQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[24].name = "ai";
TM_Qzgg5NBLvccay07XFph3Rw_7[5] = &TM_Qzgg5NBLvccay07XFph3Rw_0[28];
TM_Qzgg5NBLvccay07XFph3Rw_0[28].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[28].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, idx);
TM_Qzgg5NBLvccay07XFph3Rw_0[28].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[28].name = "idx";
TM_Qzgg5NBLvccay07XFph3Rw_7[6] = &TM_Qzgg5NBLvccay07XFph3Rw_0[29];
TM_Qzgg5NBLvccay07XFph3Rw_0[29].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[29].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, data);
TM_Qzgg5NBLvccay07XFph3Rw_0[29].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[29].name = "data";
TM_Qzgg5NBLvccay07XFph3Rw_7[7] = &TM_Qzgg5NBLvccay07XFph3Rw_0[30];
TM_Qzgg5NBLvccay07XFph3Rw_0[30].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[30].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, owner);
TM_Qzgg5NBLvccay07XFph3Rw_0[30].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[30].name = "owner";
TM_Qzgg5NBLvccay07XFph3Rw_0[19].len = 8; TM_Qzgg5NBLvccay07XFph3Rw_0[19].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[19].sons = &TM_Qzgg5NBLvccay07XFph3Rw_7[0];
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[19];
NTI_Wi7KCtOkgrq64t5MzTOrhw_.size = sizeof(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw);
NTI_Wi7KCtOkgrq64t5MzTOrhw_.kind = 17;
NTI_Wi7KCtOkgrq64t5MzTOrhw_.base = (&NTI_CJfwFDAb1ST4bu6G9bMAYbg_);
NTI_Wi7KCtOkgrq64t5MzTOrhw_.flags = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[31].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[31].offset = offsetof(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw, blob);
TM_Qzgg5NBLvccay07XFph3Rw_0[31].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[31].name = "blob";
NTI_Wi7KCtOkgrq64t5MzTOrhw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[31];
NTI_h9bIytcalWPxjGLnx0PXmCg_.size = sizeof(tyObject_FlowVarObj_Wi7KCtOkgrq64t5MzTOrhw*);
NTI_h9bIytcalWPxjGLnx0PXmCg_.kind = 22;
NTI_h9bIytcalWPxjGLnx0PXmCg_.base = (&NTI_Wi7KCtOkgrq64t5MzTOrhw_);
NTI_h9bIytcalWPxjGLnx0PXmCg_.marker = Marker_tyRef_h9bIytcalWPxjGLnx0PXmCg;
(&NTI_h9bIytcalWPxjGLnx0PXmCg_)->finalizer = (void*)fvFinalizer_Qu41eVSk9cKgFEnpH5hYc8Q;
}

