/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/luka/dev/provability_sat/nimcache/stdlib_cpuload.o /home/luka/dev/provability_sat/nimcache/stdlib_cpuload.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA {
NI calls;
};
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(NI, ncpicountProcessors)(void);
STRING_LITERAL(TM_CFWzmO8DEHxStvjr8GyqGg_2, "/proc/loadavg", 13);

N_NIMCALL(tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA* s) {
	tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig result;
	FILE* f;
	NF b;
	NI busy;
	NI total;
	NI cpus;
	result = (tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;
	f = open_hqzpWQbdA2B8l9a6wwNoP4g(((NimStringDesc*) &TM_CFWzmO8DEHxStvjr8GyqGg_2), ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	b = (NF)0;
	busy = (NI)0;
	total = (NI)0;
	fscanf(f, "%lf %lf %lf %ld/%ld", (&b), (&b), (&b), (&busy), (&total));
	close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
	cpus = ncpicountProcessors();
	{
		if (!((NI)(busy - ((NI) 1)) < cpus)) goto LA3_;
		result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((NI)(cpus * ((NI) 2)) <= (NI)(busy - ((NI) 1)))) goto LA6_;
		result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2);
	}
	goto LA1_;
	LA6_: ;
	{
		result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0);
	}
	LA1_: ;
	(*s).calls += ((NI) 1);
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void) {
}

